# Generated by Django 6.0.3 on 2026-05-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_create_account_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_History_moduel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_acc', models.CharField(max_length=12, unique=True)),
                ('reciver_acc', models.CharField(max_length=12, unique=True)),
                ('ammount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.DeleteModel(
            name='signup_model',
        ),
    ]
