# Generated by Django 6.0.6 on 2026-07-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_transaction_history_moduel_delete_signup_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_account_model',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
